# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='\u6807\u9898')),
                ('slug', models.CharField(db_index=True, default='', max_length=255, verbose_name='\u7f51\u5740')),
                ('author', models.CharField(default='', max_length=255, verbose_name='\u4f5c\u8005')),
                ('content', models.TextField(blank=True, default='', verbose_name='\u5185\u5bb9')),
                ('count', models.IntegerField(default='', verbose_name='\u7edf\u8ba1')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('published', models.BooleanField(default=True, verbose_name='\u6b63\u5f0f\u53d1\u5e03')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='\u680f\u76ee\u540d\u79f0')),
                ('slug', models.CharField(db_index=True, default='', max_length=255, verbose_name='\u680f\u76ee\u7f51\u5740')),
                ('intro', models.TextField(default='', verbose_name='\u680f\u76ee\u7b80\u4ecb')),
                ('nav_display', models.BooleanField(default=False, verbose_name='\u5bfc\u822a\u663e\u793a')),
                ('home_display', models.BooleanField(default=False, verbose_name='\u9996\u9875\u663e\u793a')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='column',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='news.Column', verbose_name='\u5206\u7c7b'),
        ),
    ]
