# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='count',
            field=models.IntegerField(default=0, verbose_name='\u7edf\u8ba1'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='\u5185\u5bb9'),
        ),
    ]
