# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20160617_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AlterModelOptions(
            name='column',
            options={},
        ),
    ]
