# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20160622_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='', max_length=256, verbose_name='\u4f5c\u8005'),
        ),
        migrations.AlterField(
            model_name='article',
            name='column',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='news.Column', verbose_name='\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.CharField(db_index=True, default='', max_length=256, verbose_name='\u7f51\u5740'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=256, verbose_name='\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(default='', max_length=256, verbose_name='\u680f\u76ee\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='column',
            name='slug',
            field=models.CharField(db_index=True, default='', max_length=256, verbose_name='\u680f\u76ee\u7f51\u5740'),
        ),
    ]
