# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idcroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(default='', max_length=255, verbose_name='\u5e8f\u5217\u53f7')),
                ('brand', models.CharField(default='', max_length=255, verbose_name='\u54c1\u724c')),
                ('model', models.CharField(default='', max_length=255, verbose_name='\u578b\u53f7')),
                ('ip', models.CharField(default='', max_length=255, verbose_name='ip')),
                ('other_ip', models.CharField(default='', max_length=255, verbose_name='\u5176\u4ed6ip')),
                ('user', models.CharField(default='', max_length=255, verbose_name='\u64cd\u4f5c\u5458')),
                ('status', models.CharField(default='product', max_length=10, verbose_name='\u72b6\u6001')),
                ('cabinet', models.CharField(default='', max_length=255, verbose_name='\u673a\u67dc')),
                ('position', models.CharField(default='', max_length=255, verbose_name='\u673a\u4f4d')),
                ('snmpcommunity', models.CharField(default='', max_length=255, verbose_name='snmp\u56e2\u4f53\u540d')),
                ('company', models.CharField(default='', max_length=255, verbose_name='\u516c\u53f8')),
                ('department', models.CharField(default='', max_length=255, verbose_name='\u90e8\u95e8')),
                ('principal', models.CharField(default='', max_length=255, verbose_name='\u8d1f\u8d23\u4eba')),
                ('comment', models.TextField(default='', verbose_name='\u5907\u6ce8')),
                ('guarantee', models.CharField(default='', max_length=255, verbose_name='\u4fdd\u4fee\u5e74\u9650')),
                ('buydate', models.CharField(default='', max_length=255, verbose_name='\u8d2d\u4e70\u65e5\u671f')),
                ('uptime', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('idcroom', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='idcroom.Idcroom', verbose_name='\u6240\u5728\u673a\u623f')),
            ],
        ),
        migrations.CreateModel(
            name='SwitchInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='\u63a5\u53e3\u540d\u79f0')),
                ('cabinet', models.CharField(default='', max_length=255, verbose_name='\u673a\u67dc')),
                ('position', models.CharField(default='', max_length=255, verbose_name='\u673a\u4f4d')),
                ('user', models.CharField(default='', max_length=255, verbose_name='\u64cd\u4f5c\u5458')),
                ('comment', models.TextField(default='', verbose_name='\u5907\u6ce8')),
                ('uptime', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('switch', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='network.Switch', verbose_name='\u6240\u5c5e\u4ea4\u6362\u673a')),
            ],
        ),
    ]
