# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u63a5\u53e3\u540d\u79f0')),
                ('cabinet', models.CharField(max_length=256, verbose_name='\u673a\u67dc')),
                ('position', models.CharField(max_length=256, verbose_name='\u673a\u4f4d')),
                ('user', models.CharField(max_length=256, verbose_name='\u64cd\u4f5c\u5458')),
                ('comment', models.TextField(default='', verbose_name='\u5907\u6ce8')),
                ('uptime', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.Switch', verbose_name='\u6240\u5c5e\u4ea4\u6362\u673a')),
            ],
        ),
    ]
