# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20160629_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='brand',
            field=models.CharField(default='', max_length=256, verbose_name='\u54c1\u724c'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='buydate',
            field=models.CharField(default='', max_length=256, verbose_name='\u8d2d\u4e70\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='cabinet',
            field=models.CharField(default='', max_length=256, verbose_name='\u673a\u67dc'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='company',
            field=models.CharField(default='', max_length=256, verbose_name='\u516c\u53f8'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='department',
            field=models.CharField(default='', max_length=256, verbose_name='\u90e8\u95e8'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='guarantee',
            field=models.CharField(default='', max_length=256, verbose_name='\u4fdd\u4fee\u5e74\u9650'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='idcroom',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='idcroom.Idcroom', verbose_name='\u6240\u5728\u673a\u623f'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='ip',
            field=models.CharField(default='', max_length=256, verbose_name='ip'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='model',
            field=models.CharField(default='', max_length=256, verbose_name='\u578b\u53f7'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='other_ip',
            field=models.CharField(default='', max_length=256, verbose_name='\u5176\u4ed6ip'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='position',
            field=models.CharField(default='', max_length=256, verbose_name='\u673a\u4f4d'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='principal',
            field=models.CharField(default='', max_length=256, verbose_name='\u8d1f\u8d23\u4eba'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='sn',
            field=models.CharField(default='', max_length=256, verbose_name='\u5e8f\u5217\u53f7'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='snmpcommunity',
            field=models.CharField(default='', max_length=256, verbose_name='snmp\u56e2\u4f53\u540d'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='user',
            field=models.CharField(default='', max_length=256, verbose_name='\u64cd\u4f5c\u5458'),
        ),
        migrations.AlterField(
            model_name='switchinterface',
            name='cabinet',
            field=models.CharField(default='', max_length=256, verbose_name='\u673a\u67dc'),
        ),
        migrations.AlterField(
            model_name='switchinterface',
            name='name',
            field=models.CharField(default='', max_length=256, verbose_name='\u63a5\u53e3\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='switchinterface',
            name='position',
            field=models.CharField(default='', max_length=256, verbose_name='\u673a\u4f4d'),
        ),
        migrations.AlterField(
            model_name='switchinterface',
            name='switch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='network.Switch', verbose_name='\u6240\u5c5e\u4ea4\u6362\u673a'),
        ),
        migrations.AlterField(
            model_name='switchinterface',
            name='user',
            field=models.CharField(default='', max_length=256, verbose_name='\u64cd\u4f5c\u5458'),
        ),
    ]
