# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20160706_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='all_ip',
            field=models.TextField(default='', verbose_name='\u5168\u90e8ip'),
        ),
    ]
