# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idcroom', '0002_auto_20160606_1427'),
        ('server', '0003_auto_20160607_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='hostname',
            field=models.CharField(default='', max_length=256, verbose_name='HOSTNAME'),
        ),
        migrations.AddField(
            model_name='server',
            name='idcroom',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='idcroom.Idcroom', verbose_name='\u6240\u5728\u673a\u623f'),
        ),
        migrations.AddField(
            model_name='server',
            name='manage_ip',
            field=models.CharField(default='', max_length=256, verbose_name='\u7ba1\u7406ip'),
        ),
        migrations.AlterField(
            model_name='server',
            name='brand',
            field=models.CharField(default='', max_length=256, verbose_name='\u54c1\u724c'),
        ),
        migrations.AlterField(
            model_name='server',
            name='buydate',
            field=models.CharField(default='', max_length=256, verbose_name='\u8d2d\u4e70\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='server',
            name='company',
            field=models.CharField(default='', max_length=256, verbose_name='\u516c\u53f8'),
        ),
        migrations.AlterField(
            model_name='server',
            name='department',
            field=models.CharField(default='', max_length=256, verbose_name='\u90e8\u95e8'),
        ),
        migrations.AlterField(
            model_name='server',
            name='guarantee',
            field=models.CharField(default='', max_length=256, verbose_name='\u4fdd\u4fee\u5e74\u9650'),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.CharField(default='', max_length=256, verbose_name='ip'),
        ),
        migrations.AlterField(
            model_name='server',
            name='model',
            field=models.CharField(default='', max_length=256, verbose_name='\u578b\u53f7'),
        ),
        migrations.AlterField(
            model_name='server',
            name='other_ip',
            field=models.CharField(default='', max_length=256, verbose_name='\u5176\u4ed6ip'),
        ),
        migrations.AlterField(
            model_name='server',
            name='position',
            field=models.CharField(default='', max_length=256, verbose_name='\u4f4d\u7f6e'),
        ),
        migrations.AlterField(
            model_name='server',
            name='principal',
            field=models.CharField(default='', max_length=256, verbose_name='\u8d1f\u8d23\u4eba'),
        ),
        migrations.AlterField(
            model_name='server',
            name='servicetype',
            field=models.CharField(default='', max_length=256, verbose_name='\u670d\u52a1\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='server',
            name='sn',
            field=models.CharField(default='', max_length=256, verbose_name='\u5e8f\u5217\u53f7'),
        ),
        migrations.AlterField(
            model_name='server',
            name='system',
            field=models.CharField(default='', max_length=256, verbose_name='\u7cfb\u7edf'),
        ),
        migrations.AlterField(
            model_name='server',
            name='user',
            field=models.CharField(default='', max_length=256, verbose_name='\u64cd\u4f5c\u5458'),
        ),
    ]
