# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idcroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diskbk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(default='', max_length=255, verbose_name='\u5e8f\u5217\u53f7')),
                ('brand', models.CharField(default='', max_length=255, verbose_name='\u54c1\u724c')),
                ('type', models.CharField(default='', max_length=255, verbose_name='\u7c7b\u578b')),
                ('capacity', models.CharField(default='', max_length=255, verbose_name='\u5bb9\u91cf')),
                ('status', models.CharField(default='backup', max_length=10, verbose_name='\u72b6\u6001')),
                ('user', models.CharField(default='', max_length=255, verbose_name='\u64cd\u4f5c\u5458')),
                ('comment', models.TextField(default='', verbose_name='\u5907\u6ce8')),
                ('guarantee', models.CharField(default='', max_length=255, verbose_name='\u4fdd\u4fee\u5e74\u9650')),
                ('buydate', models.CharField(default='', max_length=255, verbose_name='\u8d2d\u4e70\u65e5\u671f')),
                ('uptime', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('idcroom', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='idcroom.Idcroom', verbose_name='\u6240\u5728\u673a\u623f')),
            ],
        ),
        migrations.CreateModel(
            name='Memorybk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(default='', max_length=255, verbose_name='\u5e8f\u5217\u53f7')),
                ('brand', models.CharField(default='', max_length=255, verbose_name='\u54c1\u724c')),
                ('type', models.CharField(default='', max_length=255, verbose_name='\u7c7b\u578b')),
                ('capacity', models.CharField(default='', max_length=255, verbose_name='\u5bb9\u91cf')),
                ('status', models.CharField(default='backup', max_length=10, verbose_name='\u72b6\u6001')),
                ('user', models.CharField(default='', max_length=255, verbose_name='\u64cd\u4f5c\u5458')),
                ('comment', models.TextField(default='', verbose_name='\u5907\u6ce8')),
                ('guarantee', models.CharField(default='', max_length=255, verbose_name='\u4fdd\u4fee\u5e74\u9650')),
                ('buydate', models.CharField(default='', max_length=255, verbose_name='\u8d2d\u4e70\u65e5\u671f')),
                ('uptime', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('idcroom', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='idcroom.Idcroom', verbose_name='\u6240\u5728\u673a\u623f')),
            ],
        ),
        migrations.CreateModel(
            name='Serverbk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(default='', max_length=255, verbose_name='\u5e8f\u5217\u53f7')),
                ('brand', models.CharField(default='', max_length=255, verbose_name='\u54c1\u724c')),
                ('model', models.CharField(default='', max_length=255, verbose_name='\u578b\u53f7')),
                ('cpu', models.TextField(default='', verbose_name='CPU')),
                ('memory', models.TextField(default='', verbose_name='\u5185\u5b58')),
                ('disk', models.TextField(default='', verbose_name='\u786c\u76d8')),
                ('user', models.CharField(default='', max_length=255, verbose_name='\u64cd\u4f5c\u5458')),
                ('comment', models.TextField(default='', verbose_name='\u5907\u6ce8')),
                ('guarantee', models.CharField(default='', max_length=255, verbose_name='\u4fdd\u4fee\u5e74\u9650')),
                ('buydate', models.CharField(default='', max_length=255, verbose_name='\u8d2d\u4e70\u65e5\u671f')),
                ('uptime', models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('idcroom', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='idcroom.Idcroom', verbose_name='\u6240\u5728\u673a\u623f')),
            ],
        ),
    ]
