# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_auto_20160617_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default=b'', max_length=256, verbose_name=b'\xe5\x88\x86\xe7\xbb\x84\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myauth.Group', verbose_name=b'\xe6\x9d\x83\xe9\x99\x90\xe5\x88\x86\xe7\xbb\x84'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=b'', max_length=80, verbose_name=b'\xe5\xa7\x93\xe5\x90\x8d'),
        ),
    ]
